### PR TITLE
[DataGrid] Fix printable keys to match ag

### PR DESCRIPTION
**Pull request by dtassone**
Following issue mentioned in #1287

### CODE REVIEW

**Review by oliviertassinari — COMMENTED** [review]
What if the alphabet isn't the Latin one? Like a Chinese or Arabic end-user tries to enter a key?

**Comment by dtassone** [comment]
> What if the alphabet isn't the Latin one? Like a Chinese or Arabic end-user tries to enter a key?

then they should press enter first 😆 

But yeah

**Comment by oliviertassinari** [comment]
Happy to solve it in two phases. We can solve the most obvious cases with the most common latin alphabet here.
And later on, look into the long tail once a bug is open by a developer.

**Comment by dtassone** [comment]
> Happy to solve it in two phases. We can solve the most obvious cases with the most common latin alphabet here.
> And later on, look into the long tail once a bug is open by a developer.

I'm investigating. It's not that difficult, just need a good regex http://www.regular-expressions.info/unicode.html

**Review by oliviertassinari — APPROVED** [review]
It might deserve a unit test case, but not sure

**Comment by dtassone** [comment]
> It might deserve a unit test case, but not sure

there is one, but we can't repro keydown event so it's sort of covering it

**Comment by oliviertassinari** [comment]
I was thinking of a unit tests, not end-to-ends so we could cover a bunch of different keys quickly, but 👍 for waiting

**Pull request merged**
