### PR TITLE
[core] Polish issue template

### PR DESCRIPTION
**Pull request by oliviertassinari**
A follow-up on #2468, based on https://github.com/mui-org/material-ui/pull/28038

### CODE REVIEW

**Comment by oliviertassinari** [comment]
I also wonder if we shouldn't make the Order ID field more explicit around its optionality

**Review by m4theushw — APPROVED** [review]
I pushed 8f57500 with a fix for a small typo I noticed outside this PR. It looks much better now with the form inputs. 👌

**Comment by oliviertassinari** [comment]
Nice thanks for the fix, other issues were spotted on the same PR in the core repo, I will keep the two in sync and merge once both approved.

**Comment by oliviertassinari** [comment]
Nice thanks for the fix, other issues were spotted on the same PR in the core repo, I will keep the two in sync and merge once both approved.

**Pull request merged**
