### PR TITLE
[DataGrid] Remove unused `editMode` prop

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
While adding missing API docs I noticed this prop was not in use.

### CODE REVIEW

**Comment by m4theushw** [comment]
👍 for removing it. I'm repurposing this prop in #2098 to control between cell editing and row editing.

**Comment by ZeeshanTamboli** [comment]
> 👍 for removing it. I'm repurposing this prop in #2098 to control between cell editing and row editing.

Oh I see. Should I close this? You just need to change the JSDoc description. Describe it as row or cell instead of client, sever.

**Comment by m4theushw** [comment]
> Oh I see. Should I close this? You just need to change the JSDoc description. Describe it as row or cell instead of client, sever.

No, we can keep this one. The row editing feature will take some time to be ready.

**Review by flaviendelangle — APPROVED** [review]

**Comment by ZeeshanTamboli** [comment]
Can somebody look into why the CI is failing? I re-tried it multiple times.

**Comment by flaviendelangle** [comment]
@ZeeshanTamboli it's also the case on other PR's, we do have a problem.
But it's not linked to your PR :+1:

**Comment by m4theushw** [comment]
@oliviertassinari Again Netlify is failing because it didn't find a dependency we don't use. What did you do in #2140 to make it rerun?

**Review by m4theushw — APPROVED** [review]

**Comment by oliviertassinari** [comment]
> What did you do in #2140 to make it rerun?

I reverted changes done to the yarn.lock. Which is a crappy solution, hiding the problem. Since then, we changed the file in https://github.com/mui-org/material-ui-x/pull/2164. So I guess it's why it fail again. I could find https://answers.netlify.com/t/builds-always-fail-until-clearing-cache-and-re-trying/11612/13.

**Comment by m4theushw** [comment]
@oliviertassinari It's weird because I opened #2171 a couple of hours before this one and Netlify didn't fail.

Does https://answers.netlify.com/t/build-cache-is-now-updated-in-deploy-preview-builds/26344 make any sense? If this production branch's cache is wrong all PRs based on it will fail.

image

**Comment by oliviertassinari** [comment]
@m4theushw This PR is based on top of the commit that I have selected:

Capture d’écran 2021-07-20 à 23 46 42

It's pretty new.

**Comment by oliviertassinari** [comment]
@m4theushw I see that you pushed this branch to production, we will see if it solves the issue.

**Comment by m4theushw** [comment]
@oliviertassinari I clicked this "Re-run" button:

image

Only thing I noticed was this new deploy:

image

**Pull request merged**
