### PR TITLE
[DataGrid] Clean params of `onCellEditCommit`

### LINKED ISSUE #3442: [DataGrid]: Inconsistent GridCellEditCommitParams sent to onCellEditCommit handler via outside mouse click vs tab/enter
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

The first argument passed to the `onCellEditCommit` handler yields different results if you begin editing a cell and exit via mouse click vs exiting with Enter or Tab:
```tsx
<DataGrid
  rows={rows}
  columns={columns}
  onCellEditCommit={(params: GridCellEditCommitParams) => {
    // Clicking outside the cell vs enter/tab yields different results.
    console.log(params);
  }}
/>
```

The first output is what happens when you mouse click outside of the editing cell. The second output is what happens when you hit Tab/Enter while editing a cell:

Screen Shot 2021-12-15 at 7 28 27 PM

### Expected behavior 🤔

I would expect the param passed to this method to have the same `GridCellEditCommitParams` type, aka containing only `id`, `value` and `field` props.

### Steps to reproduce 🕹

Steps:

1. CodeSandbox: https://codesandbox.io/s/basiceditinggrid-material-demo-forked-d6u0m?file=/demo.tsx
2. Open the console.
3. Double-click into a cell, and click out of it. Observe the output.
4. Double-click into the same cell, and hit enter or tab. Observe the output.

### Context 🔦

I'm just getting started with DataGrid and editing behavior and noticed this. [From the docs](https://mui.com/components/data-grid/editing/#stop-editing), it's not super clear what will happen when you mousedown outside the cell (aka, is it supposed to save, or rollback?):

Screen Shot 2021-12-15 at 7 43 59 PM

Also, from the [component docs](https://mui.com/components/data-grid/editing/#server-side-persistence) and [API docs](https://mui.com/api/data-grid/data-grid/), it's not clear that `onCellEditCommit` will fire even if the cell value **hasn't** changed? Is there any way to know/prevent that from happening? I would rather prevent a PATCH call from happening if the cell value hasn't changed, but I don't see any clear way to do so at the moment.

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  System:
    OS: macOS 12.1
  Binaries:
    Node: 16.3.0 - ~/.nvm/versions/node/v16.3.0/bin/node
    Yarn: 3.0.2 - ~/.nvm/versions/node/v16.3.0/bin/yarn
    npm: 7.15.1 - ~/.nvm/versions/node/v16.3.0/bin/npm
  Browsers:
    Chrome: 96.0.4664.110
    Edge: Not Found
    Firefox: 95.0
    Safari: 15.2
  npmPackages:
    @emotion/react: ^11.7.1
    @emotion/styled: ^11.6.0
    @mui/icons-material: ^5.2.4
    @mui/material: ^5.2.4
    @mui/styles: ^5.2.3
    @mui/x-data-grid: ^5.2.0
    @mui/x-data-grid-generator: ^5.2.0
    @types/react: ^17.0.37
    @types/react-dom: ^17.0.11
    react: ^17.0.2
    react-dom: ^17.0.2
    typescript: ^4.5.4
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by valenfv**
Fixes #3442. 

## The issue
The params sent to`onCellEditCommit` callback function either when clicking outside or pressing Enter / Tab, were inconsistent.

## The solution
Clean the params to only contain `{id, field, value}`

When clicking outside of a cell in editing state, the params sent to the `publishEvent` are now the same as the ones sent when tabbing or pressing enter. 

- Given the following instance:
`<DataGrid onCellEditCommit={e => console.log(e)} rows={rows} columns={columns} />`

> 1. Edit a row and click outside
> 2. Edit a row and press Enter/Tab

Actual results: `id, field and value` are the fields received in the params

image

Solution provided by @alexfauquette

### CODE REVIEW

**Comment by alexfauquette** [comment]
Thanks for your contribution :)

@danailH The code looks good to me, but it is a solution I proposed in an issue. Could you check that it is not a problem to remove some information here?

**Comment by flaviendelangle** [comment]
cc @m4theushw

**Comment by m4theushw** [comment]
Looks good to me. I merged with `master` to fix argos.

**Comment by zigang93** [comment]
is this props onCellEditCommit been removed in v6?

**Pull request merged**
