### PR TITLE
[DataGrid] Fix TypeScript type error for toolbar components

### LINKED ISSUE #2000: Typescript type error in component GridToolbarExport after update to @material-ui/data-grid  4.0.0-alpha.32
Typescript type error in component GridToolbarExport after update version,  "error Type '{}' is missing the following properties"

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

TypeScript error is shown when I import <GridToolbarExport /> component

The error is: 
"Type '{}' is missing the following properties from type 'Pick<GridToolbarExportProps, "children" | "form" | "slot" | "style" | "title" | "color" | "translate" | "className" | "classes" | "key" | "defaultChecked" | ... 274 more ... | "csvOptions">': buttonRef, innerRef "

## Expected Behavior 🤔

On previous version I imported the component without any prop just like that : 
<GridToolbarExport />

## Steps to Reproduce 🕹

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQokscA3nXHAPSdwwAWWOLhKQAdllEx0ATwgBXOHNRYAJnQC+cIiXIABEMhhYowZABsAtHOCdhlMg3DR4bDgHETKgCoQIZgEbIUADCEJLIwOJQADTscB7A3r4BQaFmciCiqABCcjAwYbHunj5+gVAAYsBmRlC5+YVxCUllQQAiEqjAMNIAylhmWPjQRfElyeUAogAeTDCxmtqkZPqGxqaW1pwqhsgWAOaetHR0BHKi+MBhcB0gEAAUAJSscZQwclCicPdxHAA8zVKKRCYRgESiAD5fhw4ADxq0QelMjk8gUvpwoTCYXDEkDylUasZ6miuJisbDARN2p1un0BkMClBSdD-pSETM5sysX9OGzgaFwpFjGTHvR1EA

Steps:

1. Go to the url and see the error over the GridToolbarExport

## Context 🔦

I've been using  GridToolbarExport because I created a CustomToolbar. 
Recently I update material ui from : 
 "@material-ui/core": "^5.0.0-alpha.33",
    "@material-ui/data-grid": "^4.0.0-alpha.27",
    "@material-ui/icons": "^5.0.0-alpha.29",
    "@material-ui/lab": "^5.0.0-alpha.33",

to :
   "@material-ui/core": "^5.0.0-alpha.37",
    "@material-ui/data-grid": "^4.0.0-alpha.32",
    "@material-ui/icons": "^5.0.0-alpha.37",
    "@material-ui/lab": "^5.0.0-alpha.37",
    "@material-ui/styles": "^5.0.0-alpha.35",

and with this new version the component ask me for something new that I can't find in documentation 

the error says: 

"Type '{}' is missing the following properties from type 'Pick<GridToolbarExportProps, "children" | "form" | "slot" | "style" | "title" | "color" | "translate" | "className" | "classes" | "key" | "defaultChecked" | ... 274 more ... | "csvOptions">': buttonRef, innerRef  "

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
System:
    OS: macOS 11.3.1
  Binaries:
    Node: 16.2.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.13.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.114
    Edge: Not Found
    Firefox: 85.0.2
    Safari: 14.1
  npmPackages:
    @emotion/react: ^11.1.5 => 11.1.5 
    @emotion/styled: ^11.1.5 => 11.3.0 
    @material-ui/core: ^5.0.0-alpha.37 => 5.0.0-alpha.37 
    @material-ui/data-grid: ^4.0.0-alpha.32 => 4.0.0-alpha.32 
    @material-ui/icons: ^5.0.0-alpha.37 => 5.0.0-alpha.37 
    @material-ui/lab: ^5.0.0-alpha.37 => 5.0.0-alpha.37 
    @material-ui/private-theming:  5.0.0-alpha.35 
    @material-ui/styled-engine:  5.0.0-alpha.34 
    @material-ui/styles: ^5.0.0-alpha.35 => 5.0.0-alpha.35 
    @material-ui/system:  5.0.0-alpha.37 
    @material-ui/types:  6.0.1 
    @material-ui/unstyled:  5.0.0-alpha.37 
    @material-ui/utils:  5.0.0-alpha.35 
    @types/react: ^17.0.1 => 17.0.4 
    react: ^17.0.1 => 17.0.2 
    react-dom: ^17.0.1 => 17.0.2 
    typescript: ^4.1.3 => 4.2.4 

tsconfig: 

  "compilerOptions": {
    "target": "es5",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "noFallthroughCasesInSwitch": true,
    "module": "esnext",
    "moduleResolution": "node",
    "suppressImplicitAnyIndexErrors": true,
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react-jsx"
  },
  "include": [
    "src"
  ]
</details>

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #2000 

There are other duplicate closed issues #2383 and #2217 so looked important to fix it.

But I really don't understand the solution. I just copied from https://github.com/mui-org/material-ui-x/issues/2000#issuecomment-875149207. From what I researched it looks like a typescript bug for JSX due to which we need to forcibly type declare a component's props and its return type. https://github.com/microsoft/TypeScript/issues/29197#issuecomment-729651945. But do not know why it only happened after extending core component props.

Before: https://codesandbox.io/s/typescript-playground-export-forked-uwx49?file=/index.tsx
After fix: https://codesandbox.io/s/typescript-playground-export-forked-ncvb0?file=/index.tsx

Not sure how to cover it with tests. I tried typescript test but it does not work due to the `@mui/x-data-grid` under `tests` being a webpack alias does not have the generated incorrect types.

### CODE REVIEW

**Review by oliviertassinari — COMMENTED** [review]
Could we do the same for the other components? In the core, we systematically override the TypeScript definitions of the components, as they don't work as great as manual definitions

**Comment by jbty** [comment]
hello,

I still have the bug with the types of the GridToolbarFilterButton, did you find a solution?

image

have a nice day

**Comment by ZeeshanTamboli** [comment]
> I still have the bug with the types of the GridToolbarFilterButton, did you find a solution?

@jbty Yes, this PR aims to solve it.

**Comment by ZeeshanTamboli** [comment]
Is there anything left in this? I don't think so.

**Review by oliviertassinari — COMMENTED** [review]
It seems to work

**Review by m4theushw — APPROVED** [review]
> But I really don't understand the solution. I just copied from #2000 (comment).

I dove deep into this problem and I realized that these errors are coming because of incompatibility issues with v5.

Take as example the `innerRef` prop. It was removed from v5 in https://github.com/mui-org/material-ui/pull/26028, but the compiler still think it exists because the types were emitted using definitions from v4.

image

image

With that being said, I believe once we update below the version of the core to v5 we won't need to force the type anymore:

https://github.com/mui-org/material-ui-x/blob/8eabe16e899e3eaed75325442c1bdceeadd7da32/package.json#L61

For now, I'm approving and I'm okay with merging it, but in #1902 we may remove it.

**Comment by oliviertassinari** [comment]
@m4theushw In https://github.com/mui-org/material-ui-x/issues/2000#issuecomment-871757539 one of my concerns was the complexity of the generated type. I wonder if it doesn't lead to slower IntelliSense. Is this problem real and would it be solved moving to v5?

**Comment by m4theushw** [comment]
> I wonder if it doesn't lead to slower IntelliSense.

@oliviertassinari I don't know but using `as` we're overring the React types. It's the React type that generates that long union of all props. 

> Is this problem real and would it be solved when moving to v5?

If my hypothesis is right, once we upgrade to v5 we can revert this PR. I tried to upgrade it here to test, however, there are too many compiler errors to solve.

**Pull request merged**
