### PR TITLE
[DataGrid] Row ID accessor

### PR DESCRIPTION
**Pull request by me82852578**
#378 
[comment](https://github.com/mui-org/material-ui-x/issues/378#issuecomment-786371969)

### CODE REVIEW

**Comment by me82852578** [comment]
When I pull branch next, and run `yarn lint`, it show `✖ 42 problems (42 errors, 0 warnings)`, what can i do ?

**Comment by oliviertassinari** [comment]
@me82852578 The active development branch is master, not next.

**Comment by oliviertassinari** [comment]
The linked issue was fixed in #972

**Comment by me82852578** [comment]
Ohhh !  ok,  Thank you !

**Comment by oliviertassinari** [comment]
@me82852578 Thanks for spending time on it. The `getRowId` prop is only mentioned in https://material-ui.com/api/data-grid/.

**Comment by me82852578** [comment]
@oliviertassinari Sorry to bother again. 
I check #972 and #378 , found this [comment](https://github.com/mui-org/material-ui-x/issues/378#issuecomment-767876212), I think my PR is another way to solve this requirement.
Can I redo my PR based on the master branch? What do you think ?

## Summary 💡

 - It can directly specify a key in the data as a unique id of row.

 - If data doesn't exist id or need to use another key as the unique id, you can use the rowIdAccessor API to specify the key you need.

💡note: If row data have `id` and also use rowIdAccessor, rowIdAccessor priority is greater than row data id. 

## Examples 🌈

```javascript
import * as React from 'react';
import { DataGrid } from '@material-ui/data-grid';

export default function RowIdAccessorDemo() {
  return (
    <div style={{ height: 250, width: '100%' }}>
      <DataGrid
        rowIdAccessor="customUniKey"
        columns={[
          { field: 'customUniKey', width: 150 },
          { field: 'name', width: 200 },
        ]}
        rows={[
          { customUniKey: 'uniNo-1', name: 'React' },
          { customUniKey: 'uniNo-2', name: 'Material-UI' },
        ]}
      />
    </div>
  );
}
```

## Motivation 🔦

I use this solution in my project, it works good and more easier also don't need to clone each row to add the id key.

**Comment by oliviertassinari** [comment]
@me82852578 What's are the pros & cons of this API? Why is the current solution not good enough?

**Comment by me82852578** [comment]
@oliviertassinari Hi, I updated the comment, please review it again thanks !

**Comment by oliviertassinari** [comment]
@me82852578 Great. Could you open a new issue with the case EX1 that doesn't work? It looks definitely like a bug.

**Comment by me82852578** [comment]
Okay !

**Pull request closed without merging**
