### PR TITLE
[docs] Fix focus isn't set on the text box in `Edit using external button` demo

### LINKED ISSUE #1502: [DataGrid] Focus isn't set on the textbox
Focus isn't set on the textbox:

bug 2

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Fixes #1502

Not sure why `onMouseDown` doesn't work 😅 , does it stop event propagation?

Preview: https://deploy-preview-1515--material-ui-x.netlify.app/components/data-grid/editing/#edit-using-external-button

### CODE REVIEW

**Comment by ZeeshanTamboli** [comment]
Can this be reviewed?

**Comment by dtassone** [comment]
There seems to be an issue with the save button. 

1. click cell
2. click edit
3. type abc
4. click save => it doesn't save and roll back to view mode

**Comment by oliviertassinari** [comment]
I could also notice a similar issue on mobile.

**Comment by ZeeshanTamboli** [comment]
> There seems to be an issue with the save button.
> 
> 1. click cell
> 2. click edit
> 3. type abc
> 4. click save => it doesn't save and roll back to view mode

I think now it is fixed and works as expected.

**Comment by ZeeshanTamboli** [comment]
> Also, I would propose we call preventDefault when a end-user mouse down the button. This would avoid to blur the input. It currently "blink".

Can you give steps to reproduce? Maybe in a separate issue?

**Comment by ZeeshanTamboli** [comment]
> 
> Here you go, notice how the focus is move to the button as soon as I mouse down, and come back on mouse up.
> 
> steal focus

You had said:
> It currently "blink".

Where does it blink?
I don't know if I am missing something as I cannot reproduce this at https://deploy-preview-1515--material-ui-x.netlify.app/components/data-grid/editing/#edit-using-external-button. It's up to you guys to decide regarding this PR for this another issue. Relevant issue #1502 and comment https://github.com/mui-org/material-ui-x/pull/1515#issuecomment-829297366 is fixed.

**Comment by oliviertassinari** [comment]
> Where does it blink?

In my screen recording, you have ~2,000 ms between a mouse down and a mouse up. In real life, you get ~50ms, during this laps of time, the focus outline disappear and repeat again, it blinks.

**Comment by oliviertassinari** [comment]
Ok, I have fixed a couple more issues on this demo:

- remove use callback, harms DX, and is slower at runtime
- use props conventin
- fix dark mode display
- fix the single source of truth for the edit/save state
- avoid inline-style

However, there are still problems:

- enter trigger the edit mode but doesn't allow to exit it, it's inconsistent.
- the edit button doesn't account for when the focus cell is moved, handling the click event is not enough

**Comment by dtassone** [comment]
> * Enter triggers the edit mode but doesn't allow to exit it, it's inconsistent.

https://github.com/mui-org/material-ui-x/pull/1515/files#diff-2df219732ce9c9fb7f4e42b9d25717671e5591796ff69414c6f19397302cda48L84

> the edit button doesn't account for when the focus cell is moved with the keyboard arrows. Handling the click event is not enough.
need to handle `cellNavigationKeyDown`

**Comment by oliviertassinari** [comment]
> Enter triggers the edit mode but doesn't allow to exit it, it's inconsistent.

I could fix it. I have also noticed that we added Delete but didn't include Backspace, so I added it for consistency.

> need to handle cellNavigationKeyDown

@dtassone This doesn't seem straightforward. I couldn't figure it out:

- There is no `onCellNavigationKeyDown` prop, this resonates with point 1. of https://github.com/mui-org/material-ui-x/issues/1507#issuecomment-828485605.
- This event fires for any reason, it's not specific to when the cell moves. To make it work we need the id and field of the currently selected cell, we also need to know if the focused cell changed to not rerender the whole React tree on state chane. I don't know how to find this information or where to search for it.

**Comment by oliviertassinari** [comment]
> we also need to know if the focused cell changed to not rerender the whole React tree on any keydown

Actually, the event seems to only fire when the navigation key is used, I'm not completely sure, but it seems to be the case. Opened #1527 to go after the root of the pain.

**Comment by dtassone** [comment]
> > This event seems to fire for any reason, to not be specific to when the cell moves
> 
> Actually, the event seems to only fire when the navigation key is used, I'm not completely sure, but it seems to be the case. I have opened #1527 to go after the root of the pain.

Yes this is very specific event so we keep internal for advanced users.

the way to fix the issue would be something like.

```tsx
React.useEffect(()=> {
return  apiRef.current.subscribeEvent('cellNavigationKeyDown', (params)=> {
  setCellSelectedParams(params);
});
}, []);
``` 

https://material-ui.com/components/data-grid/editing/#events

**Review by dtassone — APPROVED** [review]

**Pull request merged**
