### PR TITLE
[docs] Clarify the purpose of x-grid-data-generator

### PR DESCRIPTION
**Pull request by Elius94**
~Added a Battery-Styled Renderer to draw battery percentage in a x-grid cell.~

~I don't know if it can be helpful for you, but for me is a nice cell renderer if you want to show a battery status in a device row (for example) 💯 
image~

~Thank you for that repo. It's awesome!!!~

---

Edit by @oliviertassinari, go after the root issue.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
@Elius94 Thanks for sharing, however, this `x-grid-data-generator` package is for demo purpose only. It's not meant to be used in production. We should likely update its description to mention it.

**Comment by oliviertassinari** [comment]
@Elius94 I have updated the pull request to clarify the description of the package. I think that we are good now. It's for demos only and not data grid specific (can be used for the next components to come, there is no point in managing individual packages).

**Review by oliviertassinari — APPROVED** [review]

**Review by dtassone — APPROVED** [review]

**Comment by oliviertassinari** [comment]
@Elius94 I'm glad you opened this pull request. Sorry, we couldn't accept it, maybe one day in the future, we will need a batter component for demo purposes :)

**Comment by Elius94** [comment]
No problem! Thank you for all of this beautiful framework :)

**Pull request merged**
