### PR TITLE
[DataGrid] Improve warning and docs for layouting

### LINKED ISSUE #382: [DataGrid] Doesn't seem to work within a Grid component
- [x ] The issue is present in the latest release.
- [ x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When you add the DataGrid inside of a Grid container it does what you would suspect. But if you nest it inside of

Grid container
    Grid item

It doesn't show up on the page.

Even adding a div around it with a height and width doesn't help.

## Expected Behavior 🤔

I would expect that if I am using Grid to layout my entire website adding a DataGrid control
to that Grid layout wouldn't affect the DataGrid.

## Steps to Reproduce 🕹

If you look at this CodeSandbox (https://codesandbox.io/s/musing-lalande-8e6bx?file=/src/Demo.js)

I have three examples. 

1) DataGrid inside of Grid container -> Grid item and it has a div with height and width but doesn't show the DataGrid
2) DataGrid inside of JUST a Grid container and it displays
3) DataGrid with no Grid just a wrapping div and it does display.

Steps:

1. Add Grid, DataGrid components to import
2. Add Grid, DataGrid components to file
3. Nest the DataGrid inside of Grid container and Grid item tags

## Context 🔦

We're using Grid to layout the entire project. When I nest the DataGrid inside of 

Grid container
    Grid item

tags the DataGrid doesn't display. This means I might have to just wrap the DataGrid in a div which
could effect how my page looks responsively.

## Your Environment 🌎

I see the behavior using the Official Material UI Codesandbox:

https://codesandbox.io/s/musing-lalande-8e6bx?file=/src/Demo.js

### PR DESCRIPTION
**Pull request by RobertAron**
Closes #382

### CODE REVIEW

**Comment by RobertAron** [comment]
I wasn't able to test this locally. Is there a way to import the project using something like `npm link`  to set up a sandbox to test things in?

**Comment by oliviertassinari** [comment]
@RobertAron Thanks for looking into it. We hand this repository as an extension of the main repo. What's documented in https://github.com/mui-org/material-ui/blob/next/CONTRIBUTING.md should work almost identically here.

**Review by oliviertassinari — APPROVED** [review]
I'm working on adding a CONTRIBUTING.md file. This will link the file from the main repo and detail the requirement on the CLA. For this contribution, considering that the changes were initially proposed by me. I think that we are good, no need to sign anything. Thanks!

**Comment by oliviertassinari** [comment]
Follow-up done in #406

**Review by dtassone — APPROVED** [review]

**Pull request merged**
