### PR TITLE
[DataGrid] Add elGR locale

### PR DESCRIPTION
**Pull request by clytras**
Add Greek language locale for Grid.

**WARNING**

```js
import { elGR as elGRCore } from '@material-ui/core/locale';
```

Locale `elGR` does not exist inside the current published `@material-ui/core` version `4.11.3` which this depends on (`"@material-ui/core": "^4.9.12"`), but of course it does exist inside master https://github.com/mui-org/material-ui/pull/21988.

### CODE REVIEW

**Comment by DanailH** [comment]
I think we can update to `@material-ui/core@4.11.3` otherwise we would need to maintain a copy of translations.

What do you think @oliviertassinari ?

**Comment by oliviertassinari** [comment]
@DanailH I don't understand your proposal.

**Comment by clytras** [comment]
@DanailH I was thinking about how this could work and the only way for this to work is to publish a new version of `@material-ui/core@4` that will include the `elGR` locale inside `@material-ui/core/locale` and then publish `material-ui-x` related packages having them depending to that new `@material-ui/core`, for example if we publish `@material-ui/core` version `4.12.0` that include the locale, then we'd have `@material-ui/data-grid` to bump `@material-ui/core` peer dependency to `"@material-ui/core": "^4.12.0 || ^5.0.0-alpha.22",`.

**Comment by DanailH** [comment]
Maybe I am missing something - is `elGR` released in `@material-ui/core`? I thought it is part of `@material-ui/core@4.11.3`.

**Comment by clytras** [comment]
@DanailH that's the problem, locale `elGR` does not exists inside the current released `@material-ui/core@4.11.3` version as I state in this PR OP.

**Comment by oliviertassinari** [comment]
How about we simply don't include the translation of the core? We could leave a to-do comment. It's not the last time it will happen. The solution for developers seems straightforward.

Actually, unless we change the imports to be nested, we won't be able to support any locale that isn't supported in the lowest peer dependency version of Material-UI.

**Comment by clytras** [comment]
@oliviertassinari I don't know what actual translations does Grid uses from the core locales, but I guess it does uses some thus it merges with the ones from the core locales. I'm working with it for some days now by directly using the DataGrid `localeText: GridLocaleText` and not using core locale at all, so I think it will work just fine for most cases if we don't merge it with the core locale.

How should we proceed? Should I alter this PR to have something like this then?

```js
export const elGR: Localization = getGridLocalization(elGRGrid);
```

And I'm also not sure about what to write and where for a warning comment.

**Comment by DanailH** [comment]
@clytras the `getGridLocalization` doesn't handle that case by default. It needs to be updated. If you want you can take it. I've added a possible solution below.

```diff
 export const getGridLocalization = (
   gridTranslations: Partial<GridLocaleText>,
-  coreTranslations,
+  coreTranslations?,
 ): Localization => {
   if (isMuiV5()) {
     return {
@@ -30,7 +30,7 @@ export const getGridLocalization = (
             localeText: gridTranslations,
           },
         },
-        ...coreTranslations.components,
+        ...(coreTranslations && coreTranslations.components),
       },
     };
   }
@@ -40,7 +40,7 @@ export const getGridLocalization = (
       MuiDataGrid: {
         localeText: gridTranslations,
       },
-      ...coreTranslations.props,
+      ...(coreTranslations && coreTranslations.props),
     },
   };
 };

**Comment by oliviertassinari** [comment]
@DanailH Anything against the Optional chaining?

**Comment by DanailH** [comment]
> @DanailH Anything against the optional chaining?

Nope.

**Comment by clytras** [comment]
> @clytras the `getGridLocalization` doesn't handle that case by default. It needs to be updated. If you want you can take it. I've added a possible solution below.

Yes, I'm still having JS bits about `undefined` missing functions arguments being OK!

Shouldn't this be in a seperate PR or is it fine to add it along with this PR regarding locale definitions?

I can create a new PR with the following updated `getGridLocalization`, but I'm not sure about the information comments in the documentations mentioned above.

> ```diff
>  export const getGridLocalization = (
>    gridTranslations: Partial<GridLocaleText>,
> -  coreTranslations,
> +  coreTranslations?,
>  ): Localization => {
>    if (isMuiV5()) {
>      return {
> @@ -30,7 +30,7 @@ export const getGridLocalization = (
>              localeText: gridTranslations,
>            },
>          },
> -        ...coreTranslations.components,
> +        ...(coreTranslations?.components),
>        },
>      };
>    }
> @@ -40,7 +40,7 @@ export const getGridLocalization = (
>        MuiDataGrid: {
>          localeText: gridTranslations,
>        },
> -      ...coreTranslations.props,
> +      ...(coreTranslations?.props),
>      },
>    };
>  };
> ```

**Comment by DanailH** [comment]
I'm ok with it being part of this PR.

**Comment by DanailH** [comment]
@clytras looks good. If you can just handle the conflicts and we can proceed with merging this one 😉

**Review by DanailH — APPROVED** [review]

**Pull request merged**
