### PR TITLE
[DataGrid] Add support for `classes` prop

### LINKED ISSUE #1163: [DataGrid] The CSS customization section is misleading
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

1. The "implementation of the component style " link in https://material-ui.com/api/data-grid/#css is a 404
2. The data grid fails the classes prop conformance: https://codesandbox.io/s/material-demo-forked-6n2eu?file=/demo.tsx

Screenshot 2021-03-04 at 11 00 24

## Expected Behavior 🤔

1. A working link
2. A working classes prop

## Context 🔦

The issue was reported by a user under the wrong channel (x@material-ui.com).

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

## Order id 💳

21793

### PR DESCRIPTION
**Pull request by ZeeshanTamboli**
Closes #1163 

Related to 2nd point of https://github.com/mui-org/material-ui-x/issues/1163#issuecomment-798650113.  1st point is already fixed by  #1411 .

I think I am missing something as how to compile classes `root` to string `.MuiDataGrid-root`? Will `makeStyles` convert it?

### CODE REVIEW

**Review by oliviertassinari — DISMISSED** [review]
We would need to add a test in https://github.com/mui-org/material-ui-x/blob/da4cc4fbb8d1b6cbc011ba738299383f9bfc6c07/packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx#L67-L68 as the `classes` prop is part of the standard API for all MUI components

**Comment by oliviertassinari** [comment]
> I think I am missing something as how to compile classes root to string .MuiDataGrid-root? Will makeStyles convert it?

What you did look correct, it's pretty much what we do in v5

**Comment by ZeeshanTamboli** [comment]
> We would need to add a test in
> 
> https://github.com/mui-org/material-ui-x/blob/da4cc4fbb8d1b6cbc011ba738299383f9bfc6c07/packages/grid/data-grid/src/tests/layout.DataGrid.test.tsx#L67-L68
> 
> as the `classes` prop is part of the standard API for all MUI components

Added. Not that happy with what I am testing in commit https://github.com/mui-org/material-ui-x/pull/1450/commits/3d0efa4d9506c65d0b74ad61f08b261d0101f736. Maybe you can help?

**Review by oliviertassinari — APPROVED** [review]
Approved, but my aim to not to merge any PRs that aren't mine, so somebody else will have to own this change (take accountability by merging them)

**Comment by dtassone** [comment]
it seems like we need to open another issue for row, cells and other customizable components?

**Comment by oliviertassinari** [comment]
@dtassone I think that the classes API is most relevant for DOM not that has a flat CSS specificity. Because they can be customized directly. At this point, it seems that only a few slots are like this. I would personally wait for developers complaining to expand the approach. Developers can rely on the global class names.

**Comment by dtassone** [comment]
Ok so you don't want to do what you mention here
https://github.com/mui-org/material-ui-x/pull/1448#discussion_r617456118

**Comment by oliviertassinari** [comment]
> Ok so you don't want to do what you mention here
#1448 (comment)°

I was commenting on the priorities. My point was that if the grid applies CSS with a high ma specificity, the value of adding the slot in the `classes` is low. In the long run, I think that it makes sense to have all the slots available in the classes prop, especially with unstyled.

**Comment by oliviertassinari** [comment]
@mui-org/x Anyone wants to merge this one?

**Comment by DanailH** [comment]
@ZeeshanTamboli I pushed one commit to resolve the conflicts and I will merge the PR 😉

**Review by DanailH — APPROVED** [review]

**Pull request merged**
