### PR TITLE
[core] Remove imports from `@mui/material`

### PR DESCRIPTION
**Pull request by flaviendelangle**
Fixes https://github.com/mui-org/material-ui-x/pull/3012#discussion_r743052273

### CODE REVIEW

**Comment by DanailH** [comment]
The reason why I imported it from `@mui/material` is because if you do it from `@mui/material/utils` it complains that there is no exported method.
Also `@mui/material` is used on a lot of other places to import either `unstable_composeClasses` or `generateUtilityClasses`.

**Comment by flaviendelangle** [comment]
@DanailH I saw that after creating the PR. 
I asked Olivier if he add something in mind because as it it I don't see how to avoid the root import.

**Comment by m4theushw** [comment]
You can import `generateUtilityClass` from `@mui/core`:

https://github.com/mui-org/material-ui/blob/4a67b3ce32a1a6e89d1c36b2781db460159c9f57/packages/mui-material/src/Accordion/accordionClasses.ts#L1

**Comment by oliviertassinari** [comment]
Regarding why it matters, I believe it's https://github.com/mui-org/material-ui/pull/24147.

Regarding how to fix it. I imagine we could either

1. add `@mui/core` as a dependency. 
or 
2. expose the module from `@mui/material/utils`. 

However, it won't truly solve the root cause. We are increasingly adding new modules to `@mui/core`. cc @michaldudak. I assume that ideally, we could do:

```jsx
import composeClasses from '@mui/core/composeClasses';
// or
import { composeClasses } from '@mui/core/utils';
```

**Comment by DanailH** [comment]
> Regarding how to fix it. I imagine we could either
> 
> 1. add `@mui/core` as a dependency.
>    or
> 2. expose the module from `@mui/material/utils`.

Maybe I misunderstood but there is a discussion in the process to rename `@mui/core` right? If that is true and we go with option 1. then we need to change our dep. and that will be a breaking change.

**Comment by oliviertassinari** [comment]
https://github.com/mui-org/material-ui/pull/29585

**Comment by m4theushw** [comment]
Either option 1 or 2 will be a breaking change for us. Although it might not be for MUI Core. If we add `@mui/base` as dependency, then DataGrid can only be used with MUI Core 5.1.x. I think this change will have to be postponed to v6 or v5.1.

**Comment by flaviendelangle** [comment]
I'm closing this PR since we don't have a quick solution

**Pull request closed without merging**
