### PR TITLE
[DataGrid] Fix d.ts file for data-grid

### PR DESCRIPTION
**Pull request by dtassone**

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]
A reproduction of the fail in v4.0.0-alpha.1: https://codesandbox.io/s/purple-sky-31dy0?file=/demo.tsx. 
I can confirm the fix in codesandbox: https://codesandbox.io/s/nifty-wu-ibk76?file=/demo.tsx.

**Comment by oliviertassinari** [comment]
While we are at it:

- We should prune the publish package. In the [/dist](https://unpkg.com/browse/@material-ui/data-grid@4.0.0-alpha.1/dist/) folder, we don't need:

- DataGrid.d.ts
- DataGrid.spec.d.ts
- DataGrid.test.d.ts
- data-grid.d.ts

We could solve this by using some of the publish commands of the main repo. 

- The CHANGELOG is wrong, it should copy the main one from the root folder: https://unpkg.com/browse/@material-ui/data-grid@4.0.0-alpha.1/CHANGELOG.md. We could also solve this by using some of the publish commands of the main repo.
- The published files should [include a license comment](https://unpkg.com/browse/@material-ui/core@4.11.0/index.js). We could also solve this by using some of the publish commands of the main repo.

**Comment by oliviertassinari** [comment]
Moving this comment to #299

**Comment by cherniavskii** [comment]
Fixed by https://github.com/mui/mui-x/pull/3965

**Pull request merged**
