### PR TITLE
[DataGrid] Add ptBR locale

### PR DESCRIPTION
**Pull request by erikian**
Adds the localization for Brazilian Portuguese.

### CODE REVIEW

**Comment by DanailH** [comment]
@erikian thank you for adding the locale, can you also export it here https://github.com/mui-org/material-ui-x/blob/master/packages/grid/_modules_/grid/locales/index.ts

**Comment by oliviertassinari** [comment]
And update the docs: https://deploy-preview-1077--material-ui-x.netlify.app/components/data-grid/localization/#supported-locales

**Comment by oliviertassinari** [comment]
We should translate `filterOperatorAfter` too

**Comment by erikian** [comment]
@oliviertassinari Sure, I'll make the fixes, but I haven't found the original string for filterOperatorAfter [in the file the documentation points to](https://github.com/mui-org/material-ui-x/blob/HEAD/packages/grid/_modules_/grid/constants/localeTextConstants.ts). Any directions on this?

**Comment by oliviertassinari** [comment]
I went ahead and added my native language: #1079, `filterOperatorAfter` is the opposite of `filterOperatorBefore`.

**Review by erikian — COMMENTED** [review]
run yarn prettier

**Comment by oliviertassinari** [comment]
@erikian Perfect

**Review by oliviertassinari — APPROVED** [review]

**Comment by DanailH** [comment]
The build is failing because you added a `filterOperatorAfter` key which doesn't exist.

**Review by DanailH — APPROVED** [review]

**Pull request merged**
