### PR TITLE
Fix custom footer hiding issue #821, and custom component stories

### PR DESCRIPTION
**Pull request by dtassone**

### CODE REVIEW

**Review by oliviertassinari — APPROVED** [review]
["good first issue"](https://github.com/mui-org/material-ui-x/issues?q=is%3Aissue++label%3A%22good+first+issue%22+) are meant to help onboard contributions from the community. If core team members are working on them, it makes them useless. The objective is to hopefully grow open source contributors on the MIT side. If react-table has 260 contributors, material-table 162, there is no reason we can't have a similar amount with the MIT DataGrid component.

**Comment by dtassone** [comment]
> ["good first issue"](https://github.com/mui-org/material-ui-x/issues?q=is%3Aissue++label%3A%22good+first+issue%22+) are meant to help onboard contributions from the community. If core team members are working on them, it makes them useless. The objective is to hopefully grow open source contributors on the MIT side. If react-table has 260 contributors, material-table 162, there is no reason we can't have a similar amount with the MIT DataGrid component.

I know, but as I was around the area, I felt bad not fixing it.

**Comment by DanailH** [comment]
Just a note - it makes sense to do the same for the `showToolbar` prop.

**Review by DanailH — APPROVED** [review]

**Comment by oliviertassinari** [comment]
> it makes sense to do the same for the showToolbar prop.

Aren't the toolbar and the header two different notions ? Like footer and pagination

**Comment by dtassone** [comment]
> > it makes sense to do the same for the showToolbar prop.
> 
> Aren't the toolbar and the header two different notions? Like footer and pagination, one is inside the other?
Yes it is as to override the toolbar, you have to use the header component

> 
> How about we don't touch this area as we will remove the `showToolbar` prop in the near future?

Reverted

**Comment by oliviertassinari** [comment]
@dtassone Regarding the format of the pull request, it would be better if we were following the other ones. For instance, #821 is still open. Also in the round-robin for the release, you are next, hopefully, you will see the impact of the current pull request title.

**Pull request merged**
