### PR TITLE
[DataGrid] Allow non-integer column width for flex columns

### PR DESCRIPTION
**Pull request by flaviendelangle**
Part of #2011

### CODE REVIEW

**Review by oliviertassinari — DISMISSED** [review]
I think that we miss a snapshot and a functional test case, you can find them in https://github.com/mui-org/material-ui-x/pull/2110/files

> Part of #2011

Should it be "Fix #2011" instead?

**Comment by flaviendelangle** [comment]
@oliviertassinari it does not fix entirely the issue
See https://github.com/mui-org/material-ui-x/issues/2011#issuecomment-873189677

I'll add the tests

**Review by DanailH — APPROVED** [review]

**Comment by flaviendelangle** [comment]
I have to fix the test because Safari does not round the value in the same way

**Comment by flaviendelangle** [comment]
@oliviertassinari how can I update the snapshots and merge ? 
The diff is normal here

image

**Comment by oliviertassinari** [comment]
Argos seems to have bugged

**Pull request merged**
