### PR TITLE
[DataGrid] Allow passing styles and Popper props to GridPanel

### LINKED ISSUE #1808: [DataGrid] Preferences Panel should not exceed Grid height
- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

When a user opens a preference panel (columns panel or filter panel) and the grids height is lower than the preference panels height and equals the browser windows total height, the UI jumping shown in the video below occurs. This effect also occurs, when the grid is positioned at the bottom of the browser window, with a total grid height lower than 550px.

mui-xgrid-preferences-panel

## Expected Behavior 🤔

The preferences panel height should not exceed the grids current height in order to avoid the above shown UI jumping.

## Steps to Reproduce 🕹

Steps:

1. Go to https://codesandbox.io/s/mui-preferences-panel-forked-vzsqe?file=/src/Demo.tsx:0-972
2. Resize the browser window, so that total height is lower than 550px
3. Open the columns preference panel.
4. Open the filters preference panel and add filters until the panels height exceeds the grids height.

## Order id 💳

22075

### PR DESCRIPTION
**Pull request by sebastianfrey**
Closes #1808.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
A good opportunity to add a `describeConformance` test for this component.

**Comment by sebastianfrey** [comment]
Where should I place the test? Inside `packages/grid/data-grid/src/tests/components.DataGrid.test.tsx`?

**Comment by oliviertassinari** [comment]
`/packages/grid/_modules_/grid/components/panel/GridPanel.test.tsx`

**Comment by oliviertassinari** [comment]
I have polished the PR. It should be OK now. In the future, we will likely need to add a `components` and `componentsProps` props to this component.

**Comment by sebastianfrey** [comment]
Thanks for the update. Since I had to do some priority tasks in my day to day job, I have not yet got around to write some tests.

**Comment by oliviertassinari** [comment]
I have already added a TypeScript test case. I'm adding a describe conformance, we have never used this before, time to introduce it.

**Comment by sebastianfrey** [comment]
@oliviertassinari Ah, sry for pushing my test..  I did not read your answer in time.

**Review by dtassone — APPROVED** [review]

**Review by m4theushw — APPROVED** [review]

**Comment by flaviendelangle** [comment]
https://app.circleci.com/pipelines/github/mui-org/material-ui-x/6058/workflows/52b8b247-8918-418a-831f-3440e0e27acb/jobs/31886

@oliviertassinari `getClasses` has been removed on this commit https://github.com/mui-org/material-ui/commit/2569eb9d40c648a73e62860fd993ad535ca9af5d#diff-f075d81b14df1f31fb0699c4516fe3d78490351867feeb4fb869d5dbe8c6128e

On the core, they are directly importing the classes for the component file (like we want to do in #1950)
But in the meantime do we have a better solution than copy/paste the `getClasses` that used to be in the core in our repo ?

**Comment by oliviertassinari** [comment]
@flaviendelangle I see, we got a conflict between #1994 and #2114, that broke master. `getClasses` is a trivial helper, we can add it back with a TODO v5 remove.

**Pull request merged**
