### PR TITLE
[core] Fix the support request GitHub Action

### PR DESCRIPTION
**Pull request by mnajdova**
Tested on a private repo:

image

Same as https://github.com/mui-org/material-ui/pull/29594 I also improved the message (replaced Material-UI with MUI X and changed the URL to point to mui.com), feel free to propose changes to the text.

### CODE REVIEW

**Comment by oliviertassinari** [comment]
> I also improved the message (replaced Material-UI with MUI X and changed the URL to point to mui.com)

This was because HEAD is the next branch on MUI X. I have changed the base branch.

**Comment by mnajdova** [comment]
> This was because HEAD is the next branch on MUI X (over master). I have changed the base branch.

Oopsy, totally forgot about this

**Comment by mnajdova** [comment]
@oliviertassinari you would need to remove the old GitHub App from here too if you haven't done it already.

**Comment by oliviertassinari** [comment]
Already done.

**Pull request merged**
