### PR TITLE
[DataGrid] Force scrollEndThreshold to undefined

### PR DESCRIPTION
**Pull request by flaviendelangle**

### CODE REVIEW

**Comment by m4theushw** [comment]
Although the infinite loader is a Pro feature, its hook is added to the DataGrid:

https://github.com/mui-org/material-ui-x/blob/305affa79b0723a8005cabb31026dcb9eadffdc2/packages/grid/data-grid/src/useDataGridComponent.tsx#L62

**Review by DanailH — APPROVED** [review]

**Comment by DanailH** [comment]
> Although the infinite loader is a Pro feature, its hook is added to the DataGrid:
> 
> https://github.com/mui-org/material-ui-x/blob/305affa79b0723a8005cabb31026dcb9eadffdc2/packages/grid/data-grid/src/useDataGridComponent.tsx#L62

I checked yesterday - we would need to audit the hooks that are added to the `DataGrid`. I guess that one is in both places because it was created before the split happened and it was duplicated in both places. The same goes for the `useColumnResize` one

**Comment by flaviendelangle** [comment]
@m4theushw what in the ` useGridInfiniteLoader` code stop it from working on the free version ?

**Comment by flaviendelangle** [comment]
I added an object with a strict typing so the TypeScript complains if we forget to set a forced prop.

**Comment by DanailH** [comment]
> @m4theushw what in the ` useGridInfiniteLoader` code stop it from working on the free version ?
> We can remove it from `useDataGridComponent`, I only removed `useGridColumnsReorder` but it their are other to remove we should indeed do it.

`useGridInfiniteLoader` is a paid feature only so I guess it makes sense to only be included in the `useDataGridProComponent`.

**Review by m4theushw — APPROVED** [review]

**Pull request merged**
