### PR TITLE
[DataGrid] Add Persian (faIR) locale

### PR DESCRIPTION
**Pull request by devlifeX**

### CODE REVIEW

**Comment by flaviendelangle** [comment]
Hey,
Thanks for your contribution !

Could you please add the core translations ? They seems to be available in persian
You have an equivalent here to see how it works  https://github.com/mui-org/material-ui-x/blob/next/packages/grid/_modules_/grid/locales/frFR.ts

**Comment by devlifeX** [comment]
> Hey,
> Thanks for your contribution !
> 
> Could you please add the core translations ? They seems to be available in persian
> You have an equivalent here to see how it works https://github.com/mui-org/material-ui-x/blob/next/packages/grid/_modules_/grid/locales/frFR.ts

Hey, I'm glad to contribute!
Core translations added.

**Comment by flaviendelangle** [comment]
Nice
Last thing, you can add the locale in this [file](https://github.com/mui-org/material-ui-x/blob/next/docs/src/pages/components/data-grid/localization/localization.md) so it appears in the documentation

**Comment by devlifeX** [comment]
> Nice Last thing, you can add the locale in this [file](https://github.com/mui-org/material-ui-x/blob/next/docs/src/pages/components/data-grid/localization/localization.md) so it appears in the documentation

Done.

**Review by flaviendelangle — APPROVED** [review]

**Pull request merged**
