### PR TITLE
[DataGrid] Fix `GridEditDateCell` to handle `editRowsModel` correctly

### LINKED ISSUE #3085: [DataGrid] cant enter date year with keyboard
### Duplicates

- [X] I have searched the existing issues

### Latest version

- [X] I have tested the latest version

### Current behavior 😯

image

### Expected behavior 🤔

I should be able to enter the date manually with keyboard, I can reproduce this behavior in my code and on the official documentation of the datagrid

### Steps to reproduce 🕹

Steps:

1. Edit Cell with Date Column
2. Enter Day, Month
3. Enter Year
4. Bugs out

### Context 🔦

_No response_

### Your environment 🌎

<details>
  <summary>`npx @mui/envinfo`</summary>

```
  Don't forget to mention which browser you used.
  Output from `npx @mui/envinfo` goes here.
```
</details>

### Order ID 💳 (optional)

_No response_

### PR DESCRIPTION
**Pull request by alexfauquette**
Fix #3085

The problem comes from the comparison between `valueProp` and `valueState` at each rendering.

For example, starting from date `2021` and pressing key "1"

- The state is updated and the cellUpdate event is triggered.
- The state update leads to a rerender. Since the cell value is not yet updated, `valueProp` and `valueState` are different. Then , the <input/> is rerender with value `1` and a new setState is called to set back `valueProp` (which is still 2021)
- The state is now back to 2021, the input is rerender
- The value is updated by the event. `valueProp` is now set to "1". The `valueState` will be updating

I applied a useEffect, such that modifying `valueProp` modify the `valueState` but not the opposite.

Test added in #2918 could not prevent this kind of regression, because it uses 
```js 
fireEvent.change(input, { target: { value: '0199-01-01T14:30' } });
```
To reproduce the bug in test, we need something closer to user interaction

### CODE REVIEW

**Review by flaviendelangle — APPROVED** [review]

**Comment by flaviendelangle** [comment]
Sorry I approved to fast, could you check why the tests are failing ?

**Comment by m4theushw** [comment]
Merging with `master` should fix argos. You're running with an old playwright image.

**Comment by alexfauquette** [comment]
I do not know what append to `test:coverage` I runed it on my machine, and they pass. Could it be due to yarn cache?

**Comment by m4theushw** [comment]
Wrapping `apiRef.current.setEditCellValue` in an `act` fixes the tests.

```diff
diff --git a/packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx b/packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
index b7e626948..b0773e418 100644
--- a/packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
+++ b/packages/grid/x-data-grid-pro/src/tests/editRows.DataGridPro.test.tsx
@@ -7,7 +7,7 @@ import {
   GridEditSingleSelectCell,
 } from '@mui/x-data-grid-pro';
 import Portal from '@mui/base/Portal';
-import { createRenderer, fireEvent, screen, waitFor } from '@material-ui/monorepo/test/utils';
+import { createRenderer, fireEvent, screen, waitFor, act } from '@material-ui/monorepo/test/utils';
 import { expect } from 'chai';
 import * as React from 'react';
 import { getActiveCell, getCell, getRow, getColumnHeaderCell } from 'test/utils/helperFn';
@@ -961,7 +961,9 @@ describe('<DataGridPro /> - Edit Rows', () => {
       cell.focus();
       fireEvent.doubleClick(cell);
       const newValue = new Date(2021, 6, 4);
-      apiRef.current.setEditCellValue({ id: 0, field: 'date', value: newValue });
+      act(() => {
+        apiRef.current.setEditCellValue({ id: 0, field: 'date', value: newValue });
+      });
       const input = cell.querySelector('input')!;
       await waitFor(() => {
         expect(input.value).to.equal('2021-07-04');
@@ -1074,7 +1076,9 @@ describe('<DataGridPro /> - Edit Rows', () => {
       cell.focus();
       fireEvent.doubleClick(cell);
       const newValue = new Date(2021, 6, 4, 17, 30);
-      apiRef.current.setEditCellValue({ id: 0, field: 'date', value: newValue });
+      act(() => {
+        apiRef.current.setEditCellValue({ id: 0, field: 'date', value: newValue });
+      });
       const input = cell.querySelector('input')!;
       await waitFor(() => {
         expect(input.value).to.equal('2021-07-04T17:30');
```

---


Since you're working on this component, could you apply the following the diff to improve readability? Several times I had to remember that `valueProp` is not the `value` prop, but a transformed version of it.

```diff
diff --git a/packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx b/packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
index 74d09e099..e74ac5067 100644
--- a/packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
+++ b/packages/grid/_modules_/grid/components/cell/GridEditDateCell.tsx
@@ -22,7 +22,7 @@ const useUtilityClasses = (ownerState: OwnerState) => {
 export function GridEditDateCell(props: GridRenderEditCellParams & Omit<InputBaseProps, 'id'>) {
   const {
     id,
-    value,
+    value: valueProp,
     formattedValue,
     api,
     field,
@@ -40,15 +40,15 @@ export function GridEditDateCell(props: GridRenderEditCellParams & Omit<InputBas
   const isDateTime = colDef.type === 'dateTime';
   const inputRef = React.useRef<HTMLInputElement>();
 
-  const valueProp = React.useMemo(() => {
+  const value = React.useMemo(() => {
     let parsedDate: Date | null;
 
-    if (value == null) {
+    if (valueProp == null) {
```

**Review by flaviendelangle — APPROVED** [review]

**Pull request merged**
