### PR TITLE
[docs] Add missing filterModel prop in /api/

### PR DESCRIPTION
**Pull request by imsuvesh**
I found filterModel prop is not mentioned in API docs.

### CODE REVIEW

**Comment by imsuvesh** [comment]
Also when I clicked on EDIT THIS PAGE on https://material-ui.com/api/data-grid/ , it loads a 404 page. (https://github.com/mui-org/material-ui-x/blob/master/docs/src/pages/api/data-grid/data-grid.md). 
Instead it should open - https://github.com/mui-org/material-ui-x/blob/master/docs/pages/api-docs/data-grid.md 
Can you tell me which file contains the edit this page links, I couldn't find one.

**Comment by dtassone** [comment]
Thanks for the contribution.

We missed this one, and also missed it in `x-grid.md`

**Comment by imsuvesh** [comment]
> Thanks for the contribution.
> 
> We missed this one, and also missed it in `x-grid.md`

Added PR -  https://github.com/mui-org/material-ui-x/pull/1514
Thanks

**Comment by imsuvesh** [comment]
Bundled PR created https://github.com/mui-org/material-ui-x/pull/1518
closing this one

**Pull request closed without merging**
