### PR TITLE
feat: add separator config to csv file

### PR DESCRIPTION
**Pull request by brummelte**
This way they can be opened with excel in europe too

### CODE REVIEW

**Comment by dtassone** [comment]
Any way you could expose the issue you are fixing?

**Comment by brummelte** [comment]
```
Col1,Col2,Col3,Col4,Col5,Col6
Value1,Value2,Value3,Value4,Value5,Value6
```

Open it with Excel in europe and everything is in column A:
image

Because in europe excel only understands semicolon as a separator.

```
sep=,
Col1,Col2,Col3,Col4,Col5,Col6
Value1,Value2,Value3,Value4,Value5,Value6
```

And excel in europe understands the "american" format:
image

**Comment by m4theushw** [comment]
I think you're having problems because the **List Separator** setting on Windows is not ",". This makes Excel to not parse the file correctly. The right way to import a CSV file is to use the **From Text** button. Using it you can choose a different delimiter. You can find more information on this [link](https://support.microsoft.com/en-us/office/import-or-export-text-txt-or-csv-files-5250ac4c-663c-47ce-937b-339e391393ba#ID0EAAGAAA=Newer_versions) from Microsoft. On macOS there's a [different setting](https://superuser.com/a/606274).

I'm closing this PR because it has no related issue and adding `sep=,` seems to be an Excel-specific keyword, not all spreadsheet apps support it. If you still feel it's a bug with the DataGrid feel free to open an issue so we can investigate.

image

**Comment by oliviertassinari** [comment]
I would also add that Excel support is covered in #198.

**Pull request closed without merging**
