### PR TITLE
[DataGrid] Add right click events

### PR DESCRIPTION
**Pull request by zj9495**
ref #610

### CODE REVIEW

**Comment by oliviertassinari** [comment]
This approach seems unscalable. How about we update GridSlotsComponentsProps to support new slots?

**Comment by zj9495** [comment]
> This approach seems unscalable. How about we update GridSlotsComponentsProps to support new slots?

My option is add context menu event to allow users to combine Menu component to impelement a context menu, it is easly and quickly. How about it? 
image

image

**Comment by flaviendelangle** [comment]
I would also be in favor of supporting custom row component (and exporting our component to allow basic wrappers).

**Comment by oliviertassinari** [comment]
> I would also be in favor of supporting custom row component (and exporting our component to allow basic wrappers).

@flaviendelangle To be clean, are you encouraging the following diff?

```diff
diff --git a/packages/grid/_modules_/grid/components/cell/GridCell.tsx b/packages/grid/_modules_/grid/components/cell/GridCellOwner.tsx
similarity index 100%
rename from packages/grid/_modules_/grid/components/cell/GridCell.tsx
rename to packages/grid/_modules_/grid/components/cell/GridCellOwner.tsx
diff --git a/packages/grid/_modules_/grid/models/gridSlotsComponent.ts b/packages/grid/_modules_/grid/models/gridSlotsComponent.ts
index 16d66352..b6226a01 100644
--- a/packages/grid/_modules_/grid/models/gridSlotsComponent.ts
+++ b/packages/grid/_modules_/grid/models/gridSlotsComponent.ts
@@ -30,6 +30,7 @@ import { GridPanel } from '../components/panel/GridPanel';
 import { GridColumnUnsortedIcon } from '../components/columnHeaders/GridColumnUnsortedIcon';
 import { GridApiRefComponentsProperty } from './api/gridComponentsApi';
 import { GridIconSlotsComponent } from './gridIconSlotsComponent';
+import { GridCell } from '@material-ui/data-grid';

 /**
  * Grid components React prop interface containing all the overridable components.
@@ -122,6 +123,7 @@ export const DEFAULT_GRID_SLOTS_COMPONENTS: GridApiRefComponentsProperty = {
   Footer: GridFooter,
   Header: GridHeader,
   PreferencesPanel: GridPreferencesPanel,
+  Cell: 'div',
   LoadingOverlay: GridLoadingOverlay,
   NoResultsOverlay: GridNoResultsOverlay,
   NoRowsOverlay: GridNoRowsOverlay,
```

In practice, it would mean that:

1. the author of this PR can provide his own cell slot, add his own custom event handlers.
2. we would make #2138 a bit easier to solve (to confirm with the author because he might have changed his point of view)
3. we give up on the idea to have `renderCell`/`renderEditCell` to render the **whole** cell, not only the child. https://github.com/bvaughn/react-virtualized/blob/abe0530a512639c042e74009fbf647abdb52d661/source/List/List.example.js#L200-L212

No objections. I even doubt that 3. can scale with the need to have tree data?

**Comment by Primajin** [comment]
I think that could work well, is there an easy way to play with this like in a code sandbox online? Otherwise I can  try to patch my locally installed MUI with the diff above and see if that helps

**Comment by m4theushw** [comment]
@zj9495 Do you still plan to work in this PR towards the suggestion made in https://github.com/mui-org/material-ui-x/pull/2161#issuecomment-884496507? We might even get #2138 fixed for free. I also agree that adding one more callback prop won't scale. We already have a bunch of `onCellXXX` props and some of them are not used internally. The one proposed here would fall in the same situation.

---

@Primajin You can create a [codesandbox](https://ci.codesandbox.io/status/mui-org/material-ui-x/pr/2161/builds/150983) based on the code from this PR but it won't help to play with the proposed diff. It's better to download the repo and apply the diff.

**Comment by zj9495** [comment]
> @zj9495 Do you still plan to work in this PR towards the suggestion made in [#2161 (comment)](https://github.com/mui-org/material-ui-x/pull/2161#issuecomment-884496507)? We might even get #2138 fixed for free. I also agree that adding one more callback prop won't scale. We already have a bunch of `onCellXXX` props and some of them are not used internally. The one proposed here would fall in the same situation.
> 
> @Primajin You can create a [codesandbox](https://ci.codesandbox.io/status/mui-org/material-ui-x/pr/2161/builds/150983) based on the code from this PR but it won't help to play with the proposed diff. It's better to download the repo and apply the diff.

It seems that this PR does not meet the community’s plan, let me close it

**Pull request closed without merging**
