### PR TITLE
[DataGrid] Undefined issue fix

### PR DESCRIPTION
**Pull request by visshaljagtap**

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Closing as no reproduction was provided

**Comment by visshaljagtap** [comment]
Hi @oliviertassinari no reproductions means?

**Comment by visshaljagtap** [comment]
Screenshot 2021-05-22 at 7 24 23 PM

was getting this issue

**Comment by oliviertassinari** [comment]
@visshaljagtap How did you land on this codesandbox?

**Comment by visshaljagtap** [comment]
From documentation https://material-ui.com/components/data-grid/

**Comment by oliviertassinari** [comment]
@visshaljagtap Reload

**Comment by visshaljagtap** [comment]
Now its working

**Comment by visshaljagtap** [comment]
what was the issue?

**Comment by oliviertassinari** [comment]
@visshaljagtap This breaking change was introduced by @dtassone in #1513 and released in [v4.0.0-alpha.29](https://github.com/mui-org/material-ui-x/releases/tag/v4.0.0-alpha.29).

**Comment by visshaljagtap** [comment]
Okay, thanks @oliviertassinari!

**Comment by oliviertassinari** [comment]
I have pushed new commits to fix the places where the documentation is outdated.

**Review by dtassone — APPROVED** [review]

**Pull request merged**
