### PR TITLE
[core] Fix en_US: virtualised => virtualized

### PR DESCRIPTION
**Pull request by flaviendelangle**

### CODE REVIEW

**Comment by oliviertassinari** [comment]
👍 for all the en_GB to en_US changes

**Review by oliviertassinari — APPROVED** [review]
@flaviendelangle Feel free to merge simple PRs like this. You can also ask for a review from anyone on the team. I can't find any other instances of this problem in the codebase nor the docs, so approved.

**Comment by flaviendelangle** [comment]
@oliviertassinari I think I don't have the ability to force merge without a review

**Comment by oliviertassinari** [comment]
Oh right, I'm removing this. We talk about doing it in the core but didn't in the end.

**Pull request merged**
