### PR TITLE
[DataGrid] fix missing translation key

### LINKED ISSUE #1500: [DataGrid] Error "Missing translation for key filterOperator..." when using GridToolbar filter with number column
- [x] The issue is present in the latest release.
**This issue presents in latest 4.0.0-alpha.26 and 4.0.0-alpha.25, but does not present in 4.0.0-alpha.24**

- [x] I have searched the [issues](https://github.com/mui-org/material-ui-x/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯
In DataGrid with GridToolbar using filter on column with type 'number' causes error "Missing translation for key filterOperator".

## Expected Behavior 🤔
no error

## Steps to Reproduce 🕹

Steps:

1. Go to example of using toolbar in DataGrid documentation ( https://material-ui.com/components/data-grid/filtering/#toolbar) 
2. Click on "Edit in CodeSandbox" button for this example
3. In example opened in CodeSandbox click "FILTERS" button in toolbar and clear current filter ("Commodity contains 'rice'")
4. Click FILTERS button again and set some filter for "Quantity" column (e.g. Quantity > 100)
5. Click somewhere outside of the filter (below the table). 

An error appears "Missing translation for key filterOperator>."

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
```
  Don't forget to mention which browser you used.
  Output from `npx @material-ui/envinfo` goes here.
```
</details>

### PR DESCRIPTION
**Pull request by dtassone**
fix #1500 
follow up from #1504

### CODE REVIEW

**Comment by oliviertassinari** [comment]
Please continue on Daniel PR, so we keep the history

**Comment by dtassone** [comment]
> Please continue on Daniel PR, so we keep the history, you can push to his fork. And at the very least, we should keep his commits.

Not sure it's worth the pain, as commits will get squashed anyway.

**Comment by dtassone** [comment]
Commits will get squashed.

I don't have permission to push to Danail's fork.
image

**Comment by dtassone** [comment]
Commits will get squashed.

I don't have permission to push to Danail's fork.
image

**Comment by oliviertassinari** [comment]
I assume it needs the PR to be open. I have reopend it, and it worked https://github.com/mui-org/material-ui-x/pull/1504/commits

**Comment by oliviertassinari** [comment]
One reason why I'm mentioning it is that it's important for handling contributions of the community, we can't close and restart from a custom commit each time a third-party author abandons its PR or takes weeks to answer (which happens frequently).

A second reason is so we can keep the whole conversation in the same place, it will help future iterations. We will be happy to be able to come back to the discussion in 2 years and see what was going on with this issue (it happens a couple of times every week for me in the core components, I don't why it would be different here).

**Pull request closed without merging**
