### PR TITLE
[DataGrid] Fix Popper z-index

### LINKED ISSUE #844: [DataGrid] Popper wrong z-index
When you place DataGrid in Dialog component filter options are not showing.

- [X] The issue is present in the latest release.
- [X] I have searched the [issues](https://github.com/mui-org/material-ui/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

Dialog has z-index  set to 1300 and div that filter is placed in has no z-index, so it is invisible. In console or CSS file I can manually set z-index of that div to 1400 and then I can see the filters, but I cannot type anything in input field anyway. (The same applies to XGrid)

## Expected Behavior 🤔

DataGrid placed in Dialog should work correctly with filters available.

## Steps to Reproduce 🕹

Steps:

1. Create Dialog and DataGrid or XGrid inside
2. Open the dialog
3. Click on 3 dots column menu - nothing happens
4. Click  filter icon or Density icon in Toolbar - nothing happens
5. Add to CSS `div[role="tooltip"] { z-index: 1400;}`
6. Now you can see filter and density options when you click on icons
7. Open filters and try to type any value - doesn't work

## Your Environment 🌎

<details>
  <summary>`npx @material-ui/envinfo`</summary>
  
System:
    OS: Windows 10 10.0.19042
  Binaries:
    Node: 12.16.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Chrome: 87.0.4280.141
    Edge: Spartan (44.19041.423.0), Chromium (87.0.664.75)
  npmPackages:
    @material-ui/core: 4.11.1 => 4.11.1
    @material-ui/data-grid: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/icons: 4.11.2 => 4.11.2
    @material-ui/lab: 4.0.0-alpha.57 => 4.0.0-alpha.57
    @material-ui/pickers: 3.2.10 => 3.2.10
    @material-ui/styles:  4.11.2
    @material-ui/system:  4.11.2
    @material-ui/types:  5.1.0
    @material-ui/utils:  4.11.2
    @material-ui/x-grid: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/x-grid-data-generator: ^4.0.0-alpha.15 => 4.0.0-alpha.15
    @material-ui/x-license:  4.0.0-alpha.15
    @types/react:  17.0.0
    react: ^16.13.1 => 16.14.0
    react-dom: 16.13.1 => 16.13.1
    styled-components:  4.4.1
    typescript:  3.9.7
</details>

### PR DESCRIPTION
**Pull request by m4theushw**
One chunk of #844

### CODE REVIEW

**Review by DanailH — APPROVED** [review]

**Review by dtassone — APPROVED** [review]

**Comment by oliviertassinari** [comment]
The updated reproduction with the latest commit of the PR: https://codesandbox.io/s/affectionate-tereshkova-tphdf?file=/package.json.

**Comment by TomasKomprs** [comment]
The thing is, probably not related with this fix. Filter is not working. You can't type anything in value input. 
https://codesandbox.io/s/affectionate-tereshkova-tphdf?file=/package.json.   

In MUI 4.11.1 if I test demo from docs. Filter is not working, value input seems disabled or something.

**Comment by m4theushw** [comment]
@TomasKomprs That is because the TrapFocus keeps moving the focus to the Dialog. It's fixed in V5. To work with V4 see [this comment](https://github.com/mui-org/material-ui-x/issues/844#issuecomment-800676791).

**Comment by oliviertassinari** [comment]
It seems that we didn't yet get any volunteers to take ownership of the fix by merging this PR. It looks great, @m4theushw do you want to do it? :)

**Pull request merged**
